version: "3.9"
services:
  web:
    restart: always
    ports:
      - "8888:80"
    build:
      context: ./
      dockerfile: ./apps/mukosoft/dockerfile
  backend:
    restart: always
    ports:
      - "8889:9000"
    build:
      context: ./
      dockerfile: ./apps/api/dockerfile
