name: front-end testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
            echo "Run number is $env:GITHUB_RUN_NUMBER."
      - run: |
          echo "installing dependencies"
          npm i --force
      - run: |
          echo "testing the application"
          npm run test
      - run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: |
          npx cypress install
          echo "e2e testing"
          npm run e2e
      - run: |
          echo "build application"
          npm run build --if-present
