name: "Generate version.json for MukoSoft App"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create version.json
        uses: "DamianReeves/write-file-action@master"
        with:
          path: "version.json"
          write-mode: overwrite
          contents: |
            {
              "date": "${{ github.event.repository.updated_at }}",
              "version": "0.0.${{ github.run_number }}"
            }
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "generate version.json - ${date}"
