name: "Generate version.json for MukoSoft App"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create version.json
        run: |
          touch version.json
          echo { version: ${{ github.run_number }} } >> version.json
